Countries to react
navikt/skjemabygging-formio pull request #1354
Opened 2024-11-12 13:35 UTC by lotorvik

2024-11-12 14:15 UTC, magnurh-cx requested changes
🇳🇴 🇩🇪 🇪🇸

2024-11-12 14:15 UTC, magnurh-cx commented on packages/shared-components/src/formio/components/extensions/country-select/CountrySelect.tsx
> +          value={this.getValue()}
Pass på at vi ser label (ikke f.eks NO) etter navigering fra oppsummeringssiden.

2024-11-14 12:30 UTC, akgagnat approved these changes
:norway:

2024-11-19 08:30 UTC, magnurh-cx approved these changes
🇹🇩

2024-11-25 08:03 UTC, merged