Add country select to address component
navikt/skjemabygging-formio pull request #1360
Opened 2024-11-15 14:08 UTC by lotorvik

2024-11-18 08:55 UTC, akgagnat requested changes

2024-11-18 08:55 UTC, akgagnat commented on packages/shared-components/src/components/select/Combobox.tsx
> +    const getSelectedOptions = () => {
memo

2024-11-18 08:55 UTC, akgagnat commented on packages/shared-components/src/components/select/Combobox.tsx
> +  value?: ComponentValue | string;
Kan man gjøre dette entydig?

2024-11-18 08:55 UTC, akgagnat commented on packages/shared-components/src/components/select/Combobox.tsx
> +        if (typeof value === 'string') {
For å slippe denne biten så kan vi kanskje transformere prefill-dataene ved populering slik at de ser ut slik vi forventer de? 

Altså, det objektet som sendes inn til `super.setValue` i linken nedenfor blir slik vi forventer at det ser ut i submission:
https://github.com/navikt/skjemabygging-formio/blob/master/packages/shared-components/src/formio/components/core/address/Address.tsx#L43

2024-11-19 08:28 UTC, magnurh-cx approved these changes
🇧🇳 🇺🇸 🇹🇹

2024-11-19 08:28 UTC, magnurh-cx commented on packages/fyllut/cypress/e2e/form/your-information.cy.ts
> +          cy.findByRole('combobox', { name: /Land/ }).should('exist');
Vurder å sjekke på land-verdien (USA)

2024-11-19 08:31 UTC, akgagnat approved these changes

2024-11-21 08:36 UTC, merged