Feature/add checkbox panel component from nav design
navikt/skjemabygging-formio pull request #235
Opened 2021-07-02 12:23 UTC by wen7i

2021-07-05 07:21 UTC, magnurh-cx commented on packages/fyllut/server/pdfgen.test.js
> +    });
Kanskje legge til ett par caser til? Et default case (ingen valgte verdier) og en med flere valgte, f.eks.

2021-07-05 07:49 UTC, magnurh-cx approved these changes

2021-07-05 07:49 UTC, magnurh-cx commented on packages/shared-components/src/customComponents/components/SelectBoxes.js
> +class CheckboxPanelGruppe extends SelectBoxes {
Rename klasse SelectBoxes (og prefix formio-import som SelectBoxes med Formio-)

2021-07-05 07:49 UTC, magnurh-cx commented on packages/shared-components/src/customComponents/components/SelectBoxes.js
> +        components: [descriptionPositionField, fieldSizeField],
Kommentar fra Rune: Fjern fieldSizeField

2021-07-05 07:49 UTC, magnurh-cx commented on packages/shared-components/src/template/templates/navdesign/radio/form.ejs
> +        <{{ctx.input.type}}
Sjekk om denne kan erstattes med `<input />`

2021-07-05 07:49 UTC, magnurh-cx commented on packages/shared-components/src/util/formSummaryUtil.test.js
> +    });
Legg til en default case (ingen valgte)

2021-07-05 08:03 UTC, magnurh-cx commented on packages/fyllut/server/formSummaryUtil.js
> +function handleSelectboxes(component, submission, formSummaryObject, parentContainerKey) {
Håndter ingen valgte verdier. Per nå vises tom label.

2021-07-05 08:03 UTC, magnurh-cx requested changes

2021-07-05 08:03 UTC, magnurh-cx commented on packages/shared-components/src/util/formSummaryUtil.js
> +function handleSelectboxes(component, submission, formSummaryObject, parentContainerKey, translate) {
Håndter ingen valgte verdier. Per nå vises tom label.

2021-07-07 08:08 UTC, it-vegard commented on packages/fyllut/server/formSummaryUtil.js
> +function handleSelectboxes(component, submission, formSummaryObject, parentContainerKey) {
Håndtert på linje 133-136 nå.

2021-07-07 08:09 UTC, it-vegard commented on packages/fyllut/server/pdfgen.test.js
> +    });
Lagt til under.

2021-07-07 08:10 UTC, it-vegard commented on packages/shared-components/src/util/formSummaryUtil.js
> +function handleSelectboxes(component, submission, formSummaryObject, parentContainerKey, translate) {
Håndteres nå på linje 137-140

2021-07-07 08:10 UTC, it-vegard commented on packages/shared-components/src/util/formSummaryUtil.test.js
> +    });
Lagt til under.

2021-07-07 08:26 UTC, magnurh-cx approved these changes

2021-07-07 08:28 UTC, merged