Bugfix/oversettelser i navform
navikt/skjemabygging-formio pull request #287
Opened 2021-09-17 12:40 UTC by akgagnat

Endre språk i forhåndsvisning i byggeren.
Har også skrevet om NavForm.jsx til en funksjonskomponent for å bli kvitt UNSAFE_componentWillReceiveProps.

2021-09-20 07:24 UTC, magnurh-cx requested changes

2021-09-20 07:24 UTC, magnurh-cx commented on packages/shared-components/src/components/NavForm.jsx
> -        return this.formio;
Se litt mer på dette, jf. Vegards kommentar.

2021-09-21 07:00 UTC, akgagnat commented on packages/shared-components/src/components/NavForm.jsx
> -        return this.formio;
Bruker i stedet en useEffect som setter formio.language når prop endrer seg

2021-09-21 07:20 UTC, magnurh-cx approved these changes
🐐 💨 💯 🥇

2021-09-21 07:22 UTC, merged