Bugfix/viser feilmeldinger av datovelger fødselsnummer
navikt/skjemabygging-formio pull request #354
Opened 2021-11-24 12:04 UTC by wen7i

2021-11-25 08:49 UTC, magnurh-cx requested changes
🐐

2021-11-25 08:49 UTC, magnurh-cx commented on packages/shared-components/src/customComponents/components/Fodselsnummer.jsx
>    validateFnr(fnrTekstWithMiddleSpace) {
For å oppnå bakoverkompatibilitet, ta vare på den gamle funksjonen, gjerne med en kommentar om at denne er der for å sikre bakoverkompatibilitet for eldre skjemaer. Legg ny valideringslogikk i ny funksjon med nytt navn.

2021-11-25 08:49 UTC, magnurh-cx commented on packages/shared-components/src/customComponents/components/NavDatepicker.jsx
> +  showNorwegianOrTranslation(text) {
rename param "key" instead of "text"

2021-11-25 08:49 UTC, magnurh-cx commented on packages/shared-domain/src/texts/validering.js
> +  orLaterThan: "eller senere enn",
Se om tekster kan holdes "hele" her. Bruk i stedet {{field}} el.l.

2021-11-26 08:11 UTC, magnurh-cx commented
Mona vil gjerne ha beskjed når denne er merget

2021-11-29 08:26 UTC, akgagnat approved these changes
:+1: :1st_place_medal: :100:

2021-11-29 08:27 UTC, magnurh-cx approved these changes
🐐

2021-11-29 08:32 UTC, merged