Added temporary modal and alertstripe to inform the user that digital…
navikt/skjemabygging-formio pull request #458
Opened 2022-03-17 12:29 UTC by ivankanag

Added temporary modal and alert stripe to inform the user that digital submission for mobil devices does not work

2022-03-18 09:34 UTC, magnurh-cx requested changes

2022-03-18 09:34 UTC, magnurh-cx commented on packages/fyllut/src/components/FormPage.jsx
> +    setOpenModal(true);
Sjekk hvilken device brukeren er på - User-Agents. Eller kanskje vindu-størrelse?

2022-03-18 09:34 UTC, magnurh-cx commented on packages/fyllut/src/components/FormPage.jsx
> +    setOpenModal(true);
Se på om state-håndtering kan flyttes ut fra FormPage

2022-03-18 09:34 UTC, magnurh-cx commented on packages/fyllut/src/components/ModalPrompt.jsx
> +          <Normaltekst className="margin-bottom-double">{this.props.content}</Normaltekst>
title og content må kunne oversettes

2022-03-18 09:34 UTC, magnurh-cx commented on packages/fyllut/src/components/ModalPrompt.jsx
> +                OK
Lag en constant i `TEXTS` for "OK", og legg til mulighet for å oversette her

2022-03-18 09:34 UTC, magnurh-cx commented on packages/fyllut/src/components/FormPage.jsx
> +        contentLabel="Vær obs på"
Alle tekster må legges til som konstanter i `TEXTS`

2022-03-18 09:34 UTC, magnurh-cx commented on packages/fyllut/src/components/FormPage.jsx
> +        contentLabel="Vær obs på"
Ta en demo med Rune. Han kan gi deg tekster.

2022-03-30 09:07 UTC, akgagnat approved these changes
:iphone: :warning: :medal_sports:

2022-03-30 09:08 UTC, merged