New header in builder
navikt/skjemabygging-formio pull request #585
Opened 2022-09-08 12:01 UTC by iselingu

2022-09-12 07:55 UTC, lotorvik requested changes
Se kommentarer

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/components/NavBar.jsx
> +          <HomeFilled style={{ color: "#ffffff", fontSize: "1.5rem" }} alt="Skjemaliste" />
Set fontSize med useStyle

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/components/NavBar.jsx
> +        {visSkjemaMeny && (
Lag komponent FormMenu

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/components/NavBar.jsx
> +          <div>
Lag komponent TranslationMenu

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/components/NavBar.jsx
> +        {visSkjemaMeny && (
Flytt NavBar.jsx til /components/navBar. 
Legg FormMenu og TranslationMenu i samme mappe.
FormMenu må ha form og url som properties

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/Forms/EditFormPage.jsx
> +          links: [
Bytt ut med FormMenu

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/Forms/FormPage.jsx
> +            editFormUrl={`${url}/edit`}
På EditFormPage fjern testFormUrl, formSettingsUrl, editFormUrl og bytt ut med en enkel url property.

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/Forms/FormPage.jsx
> +          <TestFormPage
Samme property endring som EditFormPage

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/Forms/FormPage.jsx
> +            formSettingsUrl={`${url}/settings`}
Samme property endring som EditFormPage

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/Forms/FormSettingsPage.jsx
> +        links: [
Bruk FormMenu istedenfor

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/Forms/TestFormPage.jsx
> +        links: [
Bruk FormMenu

2022-09-12 07:55 UTC, lotorvik commented on packages/bygger/src/components/NavBar.jsx
> +  formsLink: {
Flytt styling som ikke er i bruk her til FormMenu og FormNavigation. Vurder å splitt opp til egne komponenter på for f.eks NavLink

2022-09-15 07:23 UTC, it-vegard commented on packages/bygger/src/Forms/FormSettingsPage.jsx
>    const title = `${form.title}`;
Kan fjerne backticks (`). Blir `const title = form.title`.

2022-09-15 07:25 UTC, it-vegard commented on packages/bygger/src/components/AppLayout.jsx
> +export const AppLayout = ({ children, navBarProps, formMenuProps }) => {
Blir formMenuProps brukt noe sted her?

2022-09-15 07:28 UTC, it-vegard commented on packages/bygger/src/components/navbar/FormMenu.tsx
> +        <Settings className={styles.navBarLinkIcon} title="Tannhjul-ikon" />
Kan nok fjerne title på disse lenkene. Kan i så fall prøve `role="presentational"`

2022-09-15 07:29 UTC, it-vegard commented on packages/bygger/src/components/navbar/FormMenu.tsx
> +        <Settings className={styles.navBarLinkIcon} title="Tannhjul-ikon" />
Eller aria-hidden="true"

2022-09-15 07:31 UTC, it-vegard commented on packages/bygger/src/components/navbar/NavBar.tsx
> +          <HomeFilled style={{ color: "#ffffff", fontSize: "1.5rem" }} title="Hjem-ikon" />
Kan nok fjerne title her også.

2022-09-15 07:34 UTC, it-vegard commented on packages/bygger/src/components/navbar/NavBar.tsx
> +              <System style={{ fontSize: "1.5rem" }} title="Meny" />
Flytte font-size til css

2022-09-15 07:34 UTC, it-vegard commented on packages/bygger/src/components/navbar/NavBar.tsx
> +              <System style={{ fontSize: "1.5rem" }} title="Meny" />
Ta title også

2022-09-15 07:36 UTC, it-vegard commented on packages/bygger/src/components/navbar/TranslationsMenu.tsx
> +        ariaLabel={"Skjematekster"}
ariaLabel er overflødig (samme som teksten i lenken, og vil "overstyre"). Fjernes.

2022-09-15 07:39 UTC, it-vegard approved these changes
👍 💯 🏆 🎉 🎨

2022-09-15 09:15 UTC, merged